# backend/wrangler.toml
name = "referral-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "http://localhost:5173,https://mehedi35x.pages.dev"
BSC_RPC_URL = "https://bsc-testnet.publicnode.com"
CONTRACT_ADDRESS = "0x6938008a060E8Bef0aB9CcB1d93aCF880602fAe6"

[[d1_databases]]
binding = "DB"
database_name = "referral_db"
database_id = "33ea7916-62b6-4ec0-b2ff-efbefb1f86f9"
