# backend/wrangler.toml
name = "referral-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# Comma-separated list of allowed origins (add your production domain here)
ALLOWED_ORIGINS = "http://localhost:5173,https://mehedi35x.pages.dev"

# Use BSC Testnet RPC to match the frontend config (chainId: 97)
BSC_RPC_URL = "https://data-seed-prebsc-1-s1.binance.org:8545/"

# Must match frontend/src/config.ts
CONTRACT_ADDRESS = "0x41069AAf1DAabD4C692C3A9EdCA74f6ED6E513f1"

# Optional: starting block for event scans (set deploy block if known)
START_BLOCK = "0"

[[d1_databases]]
binding = "DB"
database_name = "referral_db"
# Replace with your actual D1 database ID
database_id = "49d6c30c-eab4-41cf-a536-6cad98bde0d8"